name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: npm install

    - name: Generate types new schema prisma
      run: npx prisma generate

    - name: Apply migrations
      run: npx prisma migrate dev

    - name: Configure AWS CLI
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set default.region us-east-1 # Ajuste a região conforme necessário

    - name: Save SSH key to file
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > /tmp/ssh_key
        chmod 400 /tmp/ssh_key

    - name: Test SSH Connectivity
      run: |
        ssh -vvv -o StrictHostKeyChecking=no -i /tmp/ssh_key $EC2_USER@$EC2_HOST "echo 'SSH Connection Successful'"

    - name: Deploy to EC2
      run: |
        ssh -i /tmp/ssh_key $EC2_USER@$EC2_HOST << EOF
          cd /home/ubuntu/nestjs-api
          git pull origin main
          npm install
          exit
        EOF
